
trigger:
- main

resources:
- repo: self
variables:
  tag: '$(Build.SourceVersion)-$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        tags: $(tag)
        containerRegistry: "devxuxu"
        repository: 'xu-helm/app-one-api'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        addPipelineData: false
        addBaseImageData: false
